{
 "title": "New dashboard",
 "time": { "from": "now", "to": "now" },
 "panels": [
  {
   "title": "Popular hour of day",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT EXTRACT(HOUR FROM \"Timestamp\") - 7 AS hour_of_day, SUM(\"Count\") AS total_count\nFROM people\nWHERE EXTRACT(DOW FROM \"Timestamp\") BETWEEN 1 AND 5\nGROUP BY EXTRACT(HOUR FROM \"Timestamp\")\nORDER BY total_count DESC\nLIMIT 1;\n"
    }
   ]
  },
  {
   "title": "Popular day of the week",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT DATE_PART('dow', \"Timestamp\") AS day_of_week, SUM(\"Count\") AS total_sum\nFROM people\nWHERE DATE_PART('dow', \"Timestamp\") BETWEEN 1 AND 5\nGROUP BY DATE_PART('dow', \"Timestamp\")\nORDER BY total_sum DESC\nLIMIT 1;\n"
    }
   ]
  },
  {
   "title": "Max crowd and corresponding time each day",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT t2.\"Timestamp\", t1.max_value\nFROM (\n    SELECT DATE(\"Timestamp\") AS date, MAX(\"Count\") AS max_value\n    FROM people\n    GROUP BY date\n) t1\nJOIN people t2 ON DATE(t2.\"Timestamp\") = t1.date AND t2.\"Count\" = t1.max_value\nORDER BY t2.\"Timestamp\";"
    }
   ]
  },
  {
   "title": "Min time and corresponding time each day",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "rawSql": "SELECT t2.\"Timestamp\", t1.min_value\nFROM (\n    SELECT DATE(\"Timestamp\") AS date, MIN(\"Count\") AS min_value\n    FROM people\n    GROUP BY date\n) t1\nJOIN people t2 ON DATE(t2.\"Timestamp\") = t1.date AND t2.\"Count\" = t1.min_value\nORDER BY t2.\"Timestamp\";"
    }
   ]
  },
  {
   "title": "Total crowd count each day",
   "type": "barchart",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "rawSql": "SELECT DATE(\"Timestamp\") AS date, SUM(\"Count\") AS total_value\nFROM people \nGROUP BY DATE(\"Timestamp\")\nORDER BY DATE(\"Timestamp\");\n"
    }
   ]
  },
  {
   "title": "Avg. Crowd count each day",
   "type": "barchart",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 43 },
   "targets": [
    {
     "rawSql": "SELECT DATE(\"Timestamp\") AS date, AVG(\"Count\") AS avg_val\nFROM people\nGROUP BY DATE(\"Timestamp\")\nORDER BY DATE(\"Timestamp\");\n"
    }
   ]
  }
 ]
}